playwright:
  viewport:
    width: 1280 # pixels
    height: 3000 # pixels

discord:
  embed:
    username: X
    avatar_url: https://about.twitter.com/content/dam/about-twitter/x/brand-toolkit/logo-black.png.twimg.1920.png
    flags: 4096 # No @here or @everyone
    color: 16711762 # ff0052

twitter:
  delays:
    no_check: 2 # seconds
    failed_login: 120 # seconds
  history_length: 200
  check_length: 20
  login:
    username: TWITTER_USERNAME
    password: TWITTER_PASSWORD

watches:
  - webhook: https://discord.com/api/webhooks/...
    history: by-author # by-account
    accounts:
      USERNAME:
        interval: 300 # seconds
        with-images: true # Send posts with images
        with-videos: true # Send posts with videos
        without-media: true # Send posts without images or videos
        posts: true # Send user-created posts
        reposts: true # Send reposts
        pinned: true # Send posts that get pinned
